# Generated by Django 4.1.2 on 2022-10-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='receiver',
        ),
    ]
