# Generated by Django 4.1.2 on 2022-10-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_owner_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
