# Generated by Django 4.1.2 on 2022-10-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_message_read_message_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
