# Generated by Django 4.1.2 on 2022-10-28 09:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_pic', max_length=255, null=True, verbose_name='image'),
        ),
    ]
