# Generated by Django 4.1.2 on 2022-10-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_alter_forum_options_discussion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
