# Generated by Django 4.1.2 on 2022-10-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_discussion_deleted_post_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
