# Generated by Django 4.1.2 on 2022-10-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_discussion_last_edited_post_last_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='description',
            new_name='content',
        ),
    ]
