# Generated by Django 4.1.2 on 2022-10-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_category_options_rename_category_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
