# Generated by Django 4.1.2 on 2022-10-28 09:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_plant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
